#ifndef	FEC_VERSION_INCLUDED
#define FEC_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define FEC_VERSION_MAJOR	3
#define FEC_VERSION_MINOR	6
#define FEC_VERSION_PATCH	0
#define FEC_VERSION_BETA	0
#define FEC_VERSION_VERSTRING	MAKE_STR(FEC_VERSION_MAJOR) "." MAKE_STR(FEC_VERSION_MINOR) "." MAKE_STR(FEC_VERSION_PATCH) "." MAKE_STR(FEC_VERSION_BETA)

inline constexpr std::string_view PE_VER = "3.1";

#endif
